global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'minitwit'
    scrape_interval: 15s
    static_configs: 
      - targets: ['minitwit:5000']
  
  - job_name: 'minitwit-api'
    scrape_interval: 15s
    static_configs: 
      - targets: ['minitwit-api:5001']